import { useEffect, useState, type FormEvent } from 'react';
import { Check, MailPlus, ShieldCheck, Trash2, UserRound, Users } from 'lucide-react';
import { supabase } from '../lib/supabase';
import './operations.css';

type TeamMember = { email: string; display_name: string | null; role: string; permissions: string[]; is_active: boolean; created_at: string };
const areas = [
  ['pages','Pages & content'],['programme','Programme'],['speakers','Speakers'],['exhibitors','Exhibitors'],['partners','Partners'],['tickets','Guest list & check-in'],['battlefield','Battlefield'],['inbox','Inbox'],['newsletter','Newsletter'],['settings','Site settings'],['team','Team & permissions'],
];
const presets: Record<string,string[]> = {
  admin: areas.map(([key]) => key), content_editor: ['pages','programme','speakers','newsletter'], programme_manager: ['programme','speakers'], partnerships: ['exhibitors','partners','inbox'], registration: ['tickets'], reviewer: ['battlefield'], viewer: [],
};
const labels: Record<string,string> = { admin:'Administrator', content_editor:'Content editor', programme_manager:'Programme manager', partnerships:'Partnerships team', registration:'Registration desk', reviewer:'Battlefield reviewer', viewer:'View only' };

export default function TeamPanel() {
  const [members,setMembers]=useState<TeamMember[]>([]); const [showForm,setShowForm]=useState(false); const [role,setRole]=useState('registration'); const [permissions,setPermissions]=useState<string[]>(presets.registration); const [message,setMessage]=useState('');
  const load=async()=>{if(!supabase)return;const{data,error}=await supabase.from('admin_email_allowlist').select('*').order('created_at');if(error)setMessage(error.message);else setMembers((data||[]) as TeamMember[])};
  useEffect(()=>{load()},[]);
  const changeRole=(value:string)=>{setRole(value);setPermissions(presets[value]||[])};
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!supabase)return;const data=new FormData(e.currentTarget);const{error}=await supabase.from('admin_email_allowlist').upsert({email:String(data.get('email')).toLowerCase(),display_name:String(data.get('name')),role,permissions,is_active:true});if(error)setMessage(error.message);else{setMessage('Team member added. They can create their account from the admin sign-in page.');setShowForm(false);e.currentTarget.reset();load()}};
  const toggle=async(member:TeamMember)=>{if(!supabase)return;await supabase.from('admin_email_allowlist').update({is_active:!member.is_active}).eq('email',member.email);load()};
  const remove=async(member:TeamMember)=>{if(!supabase||member.role==='admin')return;await supabase.from('admin_email_allowlist').delete().eq('email',member.email);load()};
  return <div className="team-layout"><section className="admin-card team-intro"><div><span>ACCESS CONTROL</span><h2>Your event team, properly organised.</h2><p>Add staff by email, assign a role, then fine-tune exactly which workspaces they can access.</p></div><button className="admin-primary" onClick={()=>setShowForm(true)}><MailPlus size={17}/> Add team member</button></section>{message&&<div className="team-message"><Check size={17}/>{message}</div>}{showForm&&<form className="admin-card team-form" onSubmit={submit}><header><div><span>NEW TEAM MEMBER</span><h2>Grant admin access</h2></div><button type="button" onClick={()=>setShowForm(false)}>Cancel</button></header><div className="field-pair"><label>Full name<input name="name" required placeholder="Team member’s name"/></label><label>Email address<input name="email" type="email" required placeholder="name@organisation.com"/></label></div><label>Role<select value={role} onChange={e=>changeRole(e.target.value)}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><fieldset><legend>Allowed admin areas</legend><div className="permission-grid">{areas.map(([key,label])=><label key={key} className={permissions.includes(key)?'selected':''}><input type="checkbox" checked={permissions.includes(key)} disabled={role==='admin'} onChange={()=>setPermissions(items=>items.includes(key)?items.filter(item=>item!==key):[...items,key])}/><ShieldCheck size={16}/><span>{label}</span></label>)}</div></fieldset><button className="admin-primary"><UserRound size={17}/> Add member</button></form>}<section className="admin-card team-list"><header><div><span>{members.length} TEAM MEMBERS</span><h2>People with admin access</h2></div></header>{members.map(member=><article key={member.email}><div className="team-avatar">{(member.display_name||member.email).slice(0,2).toUpperCase()}</div><div><strong>{member.display_name||member.email.split('@')[0]}</strong><span>{member.email}</span></div><em>{labels[member.role]||member.role}</em><span className={member.is_active?'member-active':'member-paused'}>{member.is_active?'Active':'Paused'}</span><button onClick={()=>toggle(member)}>{member.is_active?'Pause':'Restore'}</button><button className="team-delete" disabled={member.role==='admin'} onClick={()=>remove(member)}><Trash2 size={16}/></button></article>)}</section><section className="role-guide"><ShieldCheck/><div><h3>How access works</h3><p>Team members create their own password using the exact email you add here. Registration staff only see the guest list and QR check-in. You can pause access instantly without deleting their account.</p></div><Users/></section></div>;
}

